name: notebook
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  # NOTE: pip required for running tests in this repo
  - pip=20
  - cmake
  - make
  - python=3.8
# conda-lock -f environment.yml -p linux-64
